Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


seeds, num, sum = [0,1], 1, 0
begin
  seeds[0],seeds[1] = seeds[1], num
  num = seeds[0] + seeds[1]
  sum += num if num.even?
end while num <= 4000000
puts sum

